# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-06 21:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network_builder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(default='127.0.0.1/24', max_length=250)),
                ('gateway', models.GenericIPAddressField()),
            ],
        ),
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='router', max_length=250, null=True)),
                ('switch_id', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='network',
            name='router',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network_builder.Router'),
        ),
    ]
