# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-04 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_builder', '0002_auto_20170102_0502'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkbuild',
            name='log',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='networkbuild',
            name='net_instance',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='firewallrule',
            name='dl_type',
            field=models.CharField(choices=[('ARP', 'ARP'), ('IPv4', 'Ipv4')], default='IPv4', max_length=5),
        ),
    ]
