# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-06 21:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network_builder', '0002_auto_20161206_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouterAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, help_text='127.0.0.1/24', max_length=250, null=True)),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network_builder.Router')),
            ],
        ),
        migrations.AlterField(
            model_name='network',
            name='network',
            field=models.CharField(max_length=250),
        ),
    ]
