# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-08 05:00
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network_builder', '0003_auto_20161206_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Firewall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Firewall', max_length=250, null=True)),
                ('switch_id', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FirewallRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(65535)])),
                ('dl_src', models.CharField(blank=True, help_text='xx:xx:xx:xx:xx:xx', max_length=50, null=True, verbose_name='Source MAC')),
                ('dl_dst', models.CharField(blank=True, help_text='xx:xx:xx:xx:xx:xx', max_length=50, null=True, verbose_name='Destination MAC')),
                ('dl_type', models.CharField(choices=[('ARP', 'ARP'), ('Ipv4', 'Ipv4')], default='Ipv4', max_length=5)),
                ('nw_src', models.CharField(blank=True, help_text='xxx.xxx.xxx.xxx/xx', max_length=50, null=True, verbose_name='Source Address')),
                ('nw_dst', models.CharField(blank=True, help_text='xxx.xxx.xxx.xxx/xx', max_length=50, null=True, verbose_name='Destination Address')),
                ('nw_proto', models.CharField(blank=True, choices=[('TCP', 'TCP'), ('UDP', 'UDP'), ('ICMP', 'ICMP'), ('ICMPv6', 'ICMPv6')], max_length=7, null=True)),
                ('tp_src', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(65535)])),
                ('tp_dst', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(65535)])),
                ('actions', models.CharField(choices=[('ALLOW', 'ALLOW'), ('DENY', 'DENY')], max_length=6)),
                ('firewall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network_builder.Firewall')),
            ],
        ),
    ]
