# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-11 07:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network_builder', '0004_link_network_instance'),
    ]

    operations = [
        migrations.AddField(
            model_name='dhcp',
            name='default_dns',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dhcp',
            name='switch_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dhcp_static_ip',
            name='default_dns',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='bridge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='network_builder.NetworkBridge'),
        ),
    ]
