# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-08 05:57
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_builder', '0004_firewall_firewallrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src_is_dhcp', models.BooleanField(default=True)),
                ('mac', models.CharField(blank=True, help_text='xx:xx:xx:xx:xx:xx', max_length=50, null=True, verbose_name='Source MAC')),
                ('ip', models.GenericIPAddressField()),
                ('netmask', models.CharField(max_length=33)),
                ('broadcast', models.GenericIPAddressField()),
                ('speed', models.IntegerField(default=100, help_text='MB')),
            ],
        ),
        migrations.AlterField(
            model_name='firewallrule',
            name='nw_proto',
            field=models.CharField(blank=True, choices=[('TCP', 'TCP'), ('UDP', 'UDP'), ('ICMP', 'ICMP'), ('ICMPv6', 'ICMPv6')], max_length=7, null=True, verbose_name='Protocol'),
        ),
        migrations.AlterField(
            model_name='firewallrule',
            name='tp_dst',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(65535)], verbose_name='Destination Port'),
        ),
        migrations.AlterField(
            model_name='firewallrule',
            name='tp_src',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(65535)], verbose_name='Source Port'),
        ),
    ]
