# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-16 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_builder', '0005_auto_20170111_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='gateway',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
