# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-08 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_builder', '0005_auto_20161208_0557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='src_is_dhcp',
            new_name='is_dhcp',
        ),
        migrations.RemoveField(
            model_name='link',
            name='ip',
        ),
        migrations.AddField(
            model_name='link',
            name='address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='broadcast',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='netmask',
            field=models.CharField(blank=True, default='255.255.255.0', max_length=33, null=True),
        ),
    ]
