#!/bin/bash 
 
NAME="sdnctl_controller" # Name of the application 
DJANGODIR=/home/cigestion/sdn_control # Django project directory 
USER=cigestion # the user to run as 
GROUP=cigestion # the group to run as 
NUM_WORKERS=1 # how many worker processes should Gunicorn spawn 
DJANGO_SETTINGS_MODULE=sdnctl_controller.settings # which settings file should Django use 
DJANGO_WSGI_MODULE=sdnctl_controller.wsgi # WSGI module name 
 
echo "Starting $NAME as cigestion" 
 
# Activate the virtual environment 
cd $DJANGODIR 
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE 
export PYTHONPATH=$DJANGODIR: 
 
RUNDIR=. 
test -d $RUNDIR || mkdir -p $RUNDIR 
 
# Start your Django Unicorn 
# Programs meant to be run under supervisor should not daemonize themselves (do not use --daemon) 
exec /usr/bin/gunicorn ${DJANGO_WSGI_MODULE}:application \
--name $NAME \
--workers $NUM_WORKERS \
--user=$USER --group=$GROUP \
--bind=0.0.0.0:3798 \
--log-level=info \
--log-file=/home/cigestion/logs/sdnctl_controller.log

