# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 08:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sdnctl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BridgeLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base', to='sdnctl.NetworkBridge')),
                ('related_bridges', models.ManyToManyField(related_name='related_bridges', to='sdnctl.NetworkBridge')),
            ],
        ),
    ]
