# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdnctl', '0002_bridgelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='ovs',
            name='controller_url',
            field=models.CharField(default='127.0.0.1:6633', help_text='127.0.0.1:6633', max_length=256),
        ),
        migrations.AddField(
            model_name='ovs',
            name='name',
            field=models.CharField(default='OVS', max_length=256),
        ),
    ]
