# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdnctl', '0003_auto_20160816_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='ovs',
            name='administrative_ip',
            field=models.GenericIPAddressField(default='127.0.0.1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ovs',
            name='ignore_bridge',
            field=models.CharField(blank=True, help_text='coma separated name ej br0,br1', max_length=256, null=True),
        ),
    ]
