# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdnctl', '0004_auto_20160819_0709'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkbridge',
            name='admin_ifaces',
            field=models.CharField(blank=True, help_text='Coma separated name ej ens160,ens192', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='ovs',
            name='ignore_bridge',
            field=models.CharField(blank=True, help_text='Coma separated name ej br0,br1', max_length=256, null=True),
        ),
    ]
