# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 02:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sdnctl', '0005_auto_20160819_0734'),
    ]

    operations = [
        migrations.CreateModel(
            name='DHCP_Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_ip', models.GenericIPAddressField()),
                ('end_ip', models.GenericIPAddressField()),
                ('netmask', models.CharField(blank=True, max_length=33, null=True)),
                ('broadcast', models.GenericIPAddressField(blank=True, null=True)),
                ('lease_time', models.CharField(default='infinite', max_length=5)),
                ('bridge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sdnctl.NetworkBridge')),
            ],
        ),
        migrations.CreateModel(
            name='DHCP_Static_IP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=100)),
                ('address', models.GenericIPAddressField(blank=True, null=True)),
                ('hostname', models.CharField(blank=True, max_length=33, null=True)),
                ('lease_time', models.CharField(default='infinite', help_text='03m/infinite/ignore', max_length=5)),
                ('dhcp_server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sdnctl.DHCP_Server')),
            ],
        ),
    ]
