# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdnctl', '0007_auto_20160822_0218'),
    ]

    operations = [
        migrations.AddField(
            model_name='dhcp_server',
            name='address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
