# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-04 21:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sdnctl', '0008_dhcp_server_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='RyuApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default switch', max_length=256)),
                ('app_code', models.CharField(default='ryu.app.simple_switch_13', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='SDNController',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default sdn controller', max_length=256)),
                ('control_ip', models.GenericIPAddressField()),
                ('ip', models.GenericIPAddressField()),
                ('port', models.SmallIntegerField(default=6633)),
                ('apps', models.ManyToManyField(to='sdnctl.RyuApp')),
            ],
        ),
        migrations.AddField(
            model_name='ovs',
            name='controller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sdnctl.SDNController'),
        ),
    ]
