# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-05 01:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sdnctl', '0009_auto_20161204_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ovs',
            name='controller',
        ),
        migrations.RemoveField(
            model_name='ovs',
            name='controller_url',
        ),
        migrations.AddField(
            model_name='networkbridge',
            name='controller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sdnctl.SDNController'),
        ),
        migrations.AlterField(
            model_name='sdncontroller',
            name='ip',
            field=models.GenericIPAddressField(default='0.0.0.0'),
        ),
    ]
