# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-05 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdnctl', '0010_auto_20161205_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='sdncontroller',
            name='wsapi_host',
            field=models.GenericIPAddressField(blank=True, default='0.0.0.0', null=True),
        ),
        migrations.AddField(
            model_name='sdncontroller',
            name='wsapi_port',
            field=models.SmallIntegerField(default=8080),
        ),
    ]
