# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-06 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdnctl', '0011_auto_20161205_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdncontroller',
            name='wsapi_host',
            field=models.GenericIPAddressField(default='0.0.0.0'),
        ),
    ]
