# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-09 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdnctl', '0012_auto_20161206_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkbridge',
            name='base_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='networkbridge',
            name='broadcast',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='networkbridge',
            name='netmask',
            field=models.CharField(blank=True, max_length=33, null=True),
        ),
    ]
