# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-09 19:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdnctl', '0013_auto_20161209_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bridgelink',
            name='base',
        ),
        migrations.RemoveField(
            model_name='bridgelink',
            name='related_bridges',
        ),
        migrations.RemoveField(
            model_name='dhcp_server',
            name='bridge',
        ),
        migrations.RemoveField(
            model_name='dhcp_static_ip',
            name='dhcp_server',
        ),
        migrations.RemoveField(
            model_name='logical_nic',
            name='bridge',
        ),
        migrations.RemoveField(
            model_name='logical_nic',
            name='nic_ptr',
        ),
        migrations.RemoveField(
            model_name='networkbridge',
            name='controller',
        ),
        migrations.RemoveField(
            model_name='networkbridge',
            name='ovs',
        ),
        migrations.DeleteModel(
            name='BridgeLink',
        ),
        migrations.DeleteModel(
            name='DHCP_Server',
        ),
        migrations.DeleteModel(
            name='DHCP_Static_IP',
        ),
        migrations.DeleteModel(
            name='Logical_NIC',
        ),
        migrations.DeleteModel(
            name='NetworkBridge',
        ),
    ]
