# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-04 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdnctl', '0014_auto_20161209_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='sdncontroller',
            name='apps_type',
            field=models.CharField(default='router', max_length=20),
        ),
    ]
